deploy:
  stage: deploy
  image: node:18-alpine
  only:
    - master
  script:
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - yarn
    - yarn build
    - npm publish --access=restricted
